### ISSUE TITLE
Empty outfitting message

### ISSUE THREAD

**Issue by themroc5** [Marginal/EDMarketConnector#114]
From the 2.1 patchnotes:

```
Companion App
- Allow access for people who own Horizons without also owning a Season 1 SKU
- Pick up dynamic changes to which station services are available at a given market
```
Now look ath [this message](https://ross.eddb.io/eddn/log/7633736):

```
{
    "header": {
        "softwareVersion": "2.1.0.0",
         "gatewayTimestamp": "2016-05-27T20:20:07.879557",
         "softwareName": "E:D Market Connector [Windows]",
         "uploaderID": "Calebe"
    },
     "$schemaRef": "http://schemas.elite-markets.net/eddn/outfitting/1",
     "message": {
        "systemName": "LHS 397",
         "modules": [
            
        ],
         "stationName": "Thornycroft Port",
         "timestamp": "2016-05-27T20:20:15Z"
    }
}
```

I'm not sure how it was before, but could it be that no outfitting is now "fixed" as in empty list?

**Comment by Marginal** [comment]
Looks like you may be right. I wonder if this also fixes #6 and #16 - I'll need to do some testing.

EDMC sends empty outfitting messages when the API says there's no modules at stations on [this list](https://community.elitedangerous.com/galnet/uid/569f610b9657ba7d3461ba04). I'll start sending empty outfitting messages for all stations without outfitting if we can now trust the data from the API.

EDMC doesn't send empty shipyard messages because of #86 (which I don't know is fixed) or empty commodity messages.

**Comment by themroc5** [comment]
OK. I'll try to get more evidence.

**Comment by Marginal** [comment]
Since 2.12 EDMC no longer sends empty messages for stations without outfitting. So closing.
