### ISSUE TITLE
Search in Inara #enhancement

### ISSUE THREAD

**Issue by heavykick** [Marginal/EDMarketConnector#118]
Hi,

I would like to open the system and/or station in Inara. I did add a "Inara Search" function in the popUp right to "copy to clippboard".

But I am not happy with this implementation. Is a web-API available by Inara? Can we figure out the Inara Station/System-ID?
May be there is a way to automatically set "current location" automatically in Inara?

[Inara Search.patch.zip](https://github.com/Marginal/EDMarketConnector/files/293620/Inara.Search.patch.zip)

**Comment by Marginal** [comment]
I don't really use Inara but I'm happy in principal to add some kind of integration - perhaps giving you the option that clicking on the station name takes you to Inara instead of eddb, or perhaps automatically updating your location, logbook and/or fleet. But I don't think Inara has a supported API for any of these things? If you use Inara I suggest that you ask them.

**Comment by inorton** [comment]
Hi there, It would be reasonably easy to make a plugin for this. Infact I had made one a long time ago to auto-open the EDDB trade route page for each system. You should be able to do it the same way.

**Comment by Marginal** [comment]
There is a plugin for Inara [here](https://gitlab.com/mrsheepsheep/EDMC-Inara).
It gets round the lack of API by faking up form submissions.

**Comment by Marginal** [comment]
Implemented in built-in Inara support since version 2.46
