### ISSUE TITLE
Multi-account support

### ISSUE THREAD

**Issue by inorton** [Marginal/EDMarketConnector#121]
I've suddenly found myself wanting to run EDMC to populate EDSM on my second account. I'm thinking of starting multi-account support. Any ideas?

**Comment by Marginal** [comment]
I've given this some consideration, but was never motivated enough to do this myself. If you want to, please give it a go. This is as far as I got:
- Add new 'accounts' and 'passwords' config settings. These are lists of usernames and their corresponding passwords. Add support in [config.py](https://github.com/Marginal/EDMarketConnector/blob/master/config.py#L181) to get() and set() lists of strings from/to REG_MULTI_SZ entries in the Windows registry. (Hint: when get()ing a REG_MULTI_SZ value call buf.rstrip(u"\x00").split(u"\x00") to convert it to a list).
- Retain the 'username' config setting, but its usage changes to mean "last selected username".
- Search for "config.get('password')" and replace all occurrences with code that looks up the 'username' setting in the 'accounts' list, and retrieves the corresponding password from the 'passwords' list.
- In companion.py, change the cookie filename to be dependant on the 'username' setting. e.g. "cookies-" + username + ".txt". When Session.login() [detects](https://github.com/Marginal/EDMarketConnector/blob/master/companion.py#L189) that the username has changed, save, teardown and recreate the requests [session](https://github.com/Marginal/EDMarketConnector/blob/master/companion.py#L170).
- UX: Replace the Username field in preferences with a dropdown menu of existing accounts (if any), plus an extra "Add new account..." entry. ([Here](https://github.com/Marginal/EDMarketConnector/blob/master/prefs.py#L231) is an example of how to do a dropdown menu). The Password field should reflect the curently selected username.
- Migration: 
  - Add code to Config.__init__() in config.py so that if the 'username' setting exists but the 'accounts' setting does not then set 'accounts' to `[config.get('username')]`, set 'passwords' to `[config.get('password')]`, then delete the 'password' setting.
  - Add code to Session.login() in companion.py so that if the file "cookies.txt" exists, but "cookies-" + username + ".txt" does not, then rename the former to the latter.

**Comment by kaivalagi** [comment]
I just started doing a little digging on this also, I was seeing where the cmdr details were being saved/retreived and was a little surprised you were using the registry to be honest. Would it not be simpler to change the way the config is stored/retrieved, and use a config.xml file in the program folder instead? It would work the same no matter what the platform. That way if you wanted to run the app for a second account just copy it to a new location, delete the config.xml and run it afresh, creating a new config for it as a result

**Comment by kaivalagi** [comment]
Got it working with an ini file, just need to figure out how to compile it from source lol...I am used to using python from source and not compiled to a binary so need to do some reading :) For info all I did was copy the linux section which handles ini files via the RawConfigParser over the existing registry based code and edited the first few lines in the init to be:

            self.app_dir = dirname(realpath(__file__))
            if not isdir(self.app_dir):
                makedirs(self.app_dir)

            self.plugin_dir = join(self.app_dir, 'plugins')
            if not isdir(self.plugin_dir):
                mkdir(self.plugin_dir)

The above results in a EDMarketConnector.ini file existing alongside the other files...works for me :)

**Comment by Marginal** [comment]
@kaivalagi 
Glad it works for you. But that's not really a viable approach in general since:
- The directory in which packaged programs reside (i.e. under C:\Program Files, /Applications, or /usr/local/bin on Windows, MacOS or Linux) is not suitable for storing settings since it is not writeable by user programs.
- Most users don't like editing INI or XML files by hand.


> Just need to figure out how to compile it from source

See [Packaging for distribution](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source#packaging-for-distribution)

**Comment by kaivalagi** [comment]
Ok, in which case I'll leave it there for now. BTW, I don't have to edit the INI file by hand at all, the relevant app is populating the appropriate file.

If I get some more time I'll look at an alternative approach if there is a chance you would adopt it? Something along the lines you've laid out but using a single INI/XML config file in the %appdata% associated with the application and related commander it is being run for....

If this isn't to your liking then I do hope you look into something more viable for supporting multiple accounts going forwards, there are a number of players who utilise more than one account so I can see this being quite useful.

**Comment by Red13x3** [comment]
+1000 to this idea!

1) yes, I run multiple commanders. 

2) I hate dealing with the Windows registry for ANY reason and try to avoid it at length because trying to fix a setting or even removing it is worse than pulling teeth. If anyone mentions Registry to me, I immediately think it's adware/malware that is going to ruin my system when it comes time to uninstall!

3) if you are trying to make an app cross-platform, why use the Registry?? Does any other OS have such a POS way to save settings?!

Mark

--
Mark
iPhone: 0402 322 901

**Comment by Red13x3** [comment]
I'm not sure what the etiquette of GitHub is, but I really want... No... Need this to work. So, can I offer someone some money to make it happen like... this week?
And I have one other request which I will put up as another enhancement, and this too I would like implemented ASAP and I am happy to pay money.

**Comment by Red13x3** [comment]
(Sorry, these questions are coming from a user, not a programmer, so please excuse ignorance.)

Q1: If I have EDMC installed and configured with Commander 1, and I am running Elite with Commander 1, then obviously EDMC writes the data to EDSM with approriate Commander API of the trips.
But if I then log into Elite with Commander 2, and start EDMC up... What happens?  Does EDMC start sending Commander 2 data to Commander 1 entries in EDSM?

Q2: If EDMC is clever enough to NOT do the above... So then it DOES know that you are logged in with a different commander, right?

Q3. Would it not be possible to enter into EDMC mutliple EDSM API keys, for each of the commanders you have? And I assume it would also need to retain the different Elite login details to actually get the data from Elite while you are playing?  Am I oversimplifying the task as just being a table with a new record for each Commander?  You know, like a table with four fields:
1. Elite login ID
2. Elite Password
3. EDSM Username
4. EDSM API key

**Comment by inorton** [comment]
The journal now tells us which commander name we are using, so that could be a way of deciding which EDSM/Companion credentials to use.

One problem though comes from the MANY different ways people use multiple accounts with ED.

* one install, login as each account (probably most common)
* different windows users (you can run several accounts at the same time - ie, useful for dropping cargo or making videos)
* different windows users, shared game folder (make a junction to avoid having 2 copies of the game on disk)

All of these result in different locations for the journal and sometimes multiple journals for different commanders in the same folder.

**Comment by Red13x3** [comment]
>The journal now tells us which commander name we are using, so that could be a way of deciding which EDSM/Companion credentials to use.

Well that's something! Good to hear.

>MANY different ways people use multiple accounts with ED

Wow, didn't realize all those options were possible! :/
OK, so lets work through each option:

> one install, login as each account

Yep, that's the way I use it.  So I assume the Journals made by ED are always written to the same location, but with the contents showing which commander is doing the flying, right? So this is the easy way for EDMC to work with multiple commanders, right?

>different windows users 

Really? How is it possible to run multiple accounts at the same time? As in you Switch Users and it just "pauses" ED without killing the connection?? Anyway, how does that install work? One copy of ED? But the ED Journals get written to the individual Users Saved Games folder? Sooo (and this is where my lack of programming experience starts to show)... How does EDMC know where to look for the ED Journals? Isn't there some sort of system variable that holds the root of the User's data folders? So each instance of EDMC would know where the Journals are being saved to. So as you start EDMC it knows where the journals are and can read the Commander name and bam, you know which credentials to use. Right? (Sorry, I could be way off. Just guessing.)

And if that doesn't work... Well screw them, they don't need to be running EDMC when they are doing dodgy cargo swaps between their characters. :)

**Comment by kaivalagi** [comment]
That's why I would think running one app instance (seperate installs) per
account and configuring each instance and storing to a local file is the
easiest and most flexible...if sensitive data is a concern then the
password/other info could atleast be hashed...having a single location such
as the registry to store potentially multiple account data is troublesome,
that and confusion of which account is active when running two game
accounts simultaneously....

**Comment by kaivalagi** [comment]
If only we could spawn an accompanying app when launching ED....

**Comment by Marginal** [comment]
Please try [this pre-release](https://github.com/Marginal/EDMarketConnector/releases/tag/rel-226-0) and let me know how you get on.

**Comment by kaivalagi** [comment]
On switching launchers and commanders the credentials, output file location, EDSM details etc remain as they were for the originally setup commander. This happens regardless of closing/reopening between commander switching or not. It also errors with "wrong cmdr" when submitting when the credentials and the commander name are out of sync. All the setup for the commander needs to be unique for that commander and it's not.

**Comment by kaivalagi** [comment]
I'm running the pre-release you linked and it's working fine, sorry I didn't come back sooner. Any issues I'll let you know but aso far I am using different creds, EDSM, output folder locations between two accounts and it's working as it should. Thanks very very very much for this, it is appreciated!

**Comment by kaivalagi** [comment]
Just updated to 2.26 for the installable version and all okay there apart from one thing. All the settings change between commander switching except for the output file location. Is this intentional or missed. I can't say I saw this problem in the pre-release but I could have missed this. Again sorry I didn't get on this earlier...would have been useful to know this BEFORE you released lol

**Comment by Marginal** [comment]
@kaivalagi Thanks. I've changed the way that the passwords are stored since the pre-release, so you may need to re-enter passwords.

**Comment by Marginal** [comment]
> All the settings change between commander switching except for the output file location.

Didn't think of that.

**Comment by Red13x3** [comment]
Woohoo! Thanks for keeping this one alive.

You'll have it worked out, no doubt. 

CMDR Red_XIII

--
Mark
iPhone: 0402 322 901
