### ISSUE TITLE
Flight Log CSV dropped

### ISSUE THREAD

**Issue by nemesyssoft** [Marginal/EDMarketConnector#132]
Just wondering why the flight log CSV was dropped without any explanation in the latest release.

**Comment by Marginal** [comment]
Mainly because I didn't think anyone was using it (looks like I was wrong about that) and I was cleaning up the settings dialog and the code in preparation for the new functionality in E:D 2.2.

[EDSM](https://www.edsm.net/) offers much more functionality than the flight log CSV file. Is there any reason why that doesn't suit?

To migrate to EDSM:
- [Sign up](https://www.edsm.net/register)
- Enter your EDSM Commander name and API key into EDMC.
- If you still have all of your netLog files in your E:D clients' Logs folders go to "My flight logs" and choose "import netLog".
- Otherwise uninstall EDMC 2.15 and re-install EDMC 2.14. Make a jump and EDMC will upload the contents of your flight log file to EDSM in the background. This takes a while, so just leave it running.

**Comment by nemesyssoft** [comment]
I already have EDSM setup. I liked the log because it saves more details about the trip, like which ship I was flying, what was my cargo, etc.

**Comment by Redwalljp** [comment]
Evening. I just started using EDMC 2.16 and found that I couldn't even enter my Commander name or API. The checkbox and entry fields were grayed out in 2.16. I replaced it with 2.14 and can add my logs to EDSM automatically now.

Is there any chance that function will be re-implemented?
I'm a member of the SWE expedition and out of the 150 plus members, 30 of us so far have signed up to use EDSM (and EDMC to record our progress). I wouldn't be surprised if interest in the function grew.

**Comment by Marginal** [comment]
I'm sorry but the flight log CSV file isn't coming back.
- Use the EDMC's EDSM integration to track your flight history.
- Hopefully someone will use the new Commander's Log journal coming in E:D 2.2 to write an app that will track your ship, cargo etc.

**Comment by Marginal** [comment]
[This](https://github.com/Marginal/EDMCFlightLog) EDMC plugin updates the "Flight Log.csv" file in the same way as EDMC versions prior to 2.15.

**Comment by nemesyssoft** [comment]
Thanks!

-Laurent.
-- 
Laurent Daudelin laurent@nemesys-soft.com
AIM/iChat/Skype:*LaurentDaudelin*  http://www.nemesys-soft.com/
Logiciels Nemesys Software
