### ISSUE TITLE
Unable to enter credentials

### ISSUE THREAD

**Issue by Disorganise** [Marginal/EDMarketConnector#190]
Hi,
I updated to 2.3 via auto update and it seemed to lose my details.  So I uninstalled and downloaded manually and installed again.
But I'm unable to enter credentials because the boxes are greyed out
thanks

**Comment by Disorganise** [comment]
Reverting to version 224 allows me to add credentials so it seems to be the 230 build

**Comment by Disorganise** [comment]
I tried 226 also, get the same problem.  But 225 works ok.  They also prevent me entering the EDSM key

**Comment by Marginal** [comment]
See [here](https://github.com/Marginal/EDMarketConnector/wiki/Troubleshooting#credentials-settings-are-greyed-out) - check that the “E:D journal file location” setting is pointing to the location of the Journal files on the machine running E:D.

**Comment by grocal** [comment]
It's due to adding commander recognition AKA profile. Just start actual ED game (be in some starport for example not in menu) and then start EDMC. It should recognize your commander tag and allow you to enter credentials. Then you will be asked to enter security code from email. I had a small problem with window for this security code not disappearing after entering proper code but restarting EDMC did the job.
