### ISSUE TITLE
plugin hook to know when eddb or edsm are updated?

### ISSUE THREAD

**Issue by inorton** [Marginal/EDMarketConnector#213]
The eddb and edsm modules can update their services at any time, it would be nice to have some form of notifications queue that these could publish to, then a plugin could subscribe to these notifications.  The same could be useful for errors.

I'm really thinking that EDSMOverlay could print quick little "EDDB updated" messages occasionally using this.

How does this sound for an idea?

**Comment by Marginal** [comment]
The eddb module doesn't query eddb - mainly because there's no API to do so and themroc has no interest in providing one - so I don't see any way to tell whether the do has been updated recently.

The EDSM module does query EDSM to write log and obtain the system's "new" status for display. Is the latter of interest?

**Comment by inorton** [comment]
I'm more really just thinking a means of EDMC to announce it has done some thing, eg, having just uploaded the market data.

**Comment by Marginal** [comment]
So some kind of `internal_event()` callback, with various event types?

**Comment by NoFoolLikeOne** [comment]
I was just thinking about this.  I guess not strictly the subject of the OP 

I have a few plugins that I'm planning on writing the would need to get system data from EDSM.  But if EDMC has already queried to find out if the system it would be better to pass the query results as an event to all plugins instead of having each plugin having to make the call itself.

The event might look something like this..

```{
    event:  "edsmQuery",
    result: "success\failure"
    name            : "Merope",
    coords          : {
        x               : -78.59375,
        y               : -149.625,
        z               : -340.53125
    },
    information     : {
        allegiance      : "Federation",
        government      : "Democracy",
        faction         : "Pleiades Resource Enterprise",
        factionState    : "Expansion",
        population      : 850000,
        reserve         : "Pristine",
        security        : "Medium",
        economy         : "Industrial"
    },
    primaryStar     : {
        type            : "B (Blue-White) Star",
        name            : "Merope",
        isScoopable     : true
    }
}```

Then any installed plugin would be able to use the results without having to interface with EDSM as all.

**Comment by inorton** [comment]
Could you get the same data from eddb? Your app could be fed in real-time by the zeromq feed

**Comment by NoFoolLikeOne** [comment]
@inorton  wrote:
> Could you get the same data from eddb? Your app could be fed in real-time by the zeromq feed

I was making an assumption about how EDMC was finding out if the system was undiscovered. I thought it would be calling the systems API https://www.edsm.net/en/api-v1#endPointSystem which could provide all that information.  But looking through the code I see it is using another mechanism. 

I still think it would be a useful thing to do.

The plugin I am currently working on looks up the nearest Neutron star.
Another I am planning will display population and alliegence info
If a change request I put in to EDSM is accepted we could also a traffic report plugin

Each of those plugins would independently make a call to the same EDSM API

**Comment by Marginal** [comment]
EDSM and Inara callbacks documented at https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md#plugin-specific-events
