### ISSUE TITLE
Fails to start - Windows 10 64bit

### ISSUE THREAD

**Issue by XeonBlue** [Marginal/EDMarketConnector#218]
I am attempting to run release 2.33 on Windows 10.. app seems to install correctly, but when I attempt to run it, there is no feedback at all.  It appears for a moment in the task manager, but immediately closes.  I have attempted running as administrator and not admin, I have tried the prior version of the app, no luck.

I saw elsewhere to attempt turning off virus scanner, but that made no difference for me as far as I could tell.
Also saw some people commenting about a failed install..this did not appear to be my issue, but I tried the solution requested (visit https://support.microsoft.com/en-us/help/947821/fix-windows-update-errors-by-using-the-dism-or-system-update-readiness-tool) but that did not help either.

**Comment by Marginal** [comment]
Please attach the file `%TMP%\EDMarketConnector.log`.

**Comment by XeonBlue** [comment]
[EDMarketConnector.txt](https://github.com/Marginal/EDMarketConnector/files/1034599/EDMarketConnector.txt)

**Comment by Marginal** [comment]
It appears that you have CSR's "BlueSuite" installed, and it's [screwing around](http://sw.rucsok.hu/tkinter/tclenvar.html) with your environment variables. I will put a workaround in the next release.

Do you need "BlueSuite"? If not, please try uninstalling it.
Otherwise, or if that doesn't help, please delete the "TCL_LIBRARY" [environment variable](https://support.shotgunsoftware.com/hc/en-us/articles/114094235653-Setting-global-environment-variables-on-Windows).

**Comment by XeonBlue** [comment]
Aha.. Nope, not anymore.. I will uninstall.  Thanks.
