### ISSUE TITLE
Ship loadout for coriolis does not produce output that can be imported on coriolis

### ISSUE THREAD

**Issue by lemmy04** [Marginal/EDMarketConnector#229]
I've set EDMarketConnector to produce ship loadout exports for coriolis.io, but when I try to import one it tells me "builds must be an object".

**Comment by Marginal** [comment]
Check that you're using a recent version of EDMC and that you're using the Coriolis clone at https://coriolis.edcd.io/ (since https://coriolis.io/ is no longer maintained - see [here](https://coriolis.edcd.io/about) for how to bring your builds across).

BTW you can jump straight to your build in Coriolis by clipping on your ship name in EDMC's main window. Choose "Coriolis" as your Preferred Shipyard on the "Configuration" settings tab.

**Comment by lemmy04** [comment]
Didn't know about coriolis.io being deprecated... the ED:MC exports work fine with the new site zou mentioned.
Thanks!
