### ISSUE TITLE
Not starting, requires accurate timestamp

### ISSUE THREAD

**Issue by bsaerens** [Marginal/EDMarketConnector#233]
Once updated an error message pops up:
"This app requires accurate timestamps.
Check you system's Date and Time settings."

As far as I know all my date and time settings are automatic. I've had this happen in a previous version as well and couldn't get it to work until the next update.

**Comment by Marginal** [comment]
The app requires that your clock is accurate to within a minute or two. The easiest way to do this is to check "Set time automatically" and maybe "Set time zone automatically" in your system's Date & Time settings.

Otherwise, please start a Command Prompt and copy and paste the following in to it:
```cmd
powershell -Command "Get-Date -Format o; (Invoke-WebRequest https://eddn.edcd.io:4430/health_check/).Headers"
```
Press Enter, and copy the result and paste them back here.

**Comment by bsaerens** [comment]
Turns out my clock was indeed out of sync, though it was set to automatic. Synced it and it is back in working order. Thanks.
