### ISSUE TITLE
game login information

### ISSUE THREAD

**Issue by aDigitalPhantom** [Marginal/EDMarketConnector#285]
This should not use my login information. I can get all the information I want to use this for from the log files. The only reason I looked at this was to update a website. I'm not willing to use my game login information in a 3rd party tool. I don't have the time to remove this useless requirement.

**Comment by Marginal** [comment]
Feel free to

**Comment by aDigitalPhantom** [comment]
So sending private information to some place other than the game is the way this is designed?

**Comment by AnthorNet** [comment]
Nothing is send anywhere, the credentials are only required to connect to the Frontier API.
No need to be offensive.

**Comment by Marginal** [comment]
And access to the Frontier API is required to feed Inara and other sites with station market data.

**Comment by Nazosan** [comment]
Even assuming your software is 100% reliable and safe, isn't there always some remote possibility some third party could in some way exploit it?  Given that this gives them full absolute access to your account this could be devastating.  (Yes, it might also be technically possible the game or its launcher might be exploitable, but I'd rather one danger than two.)

As for "needed" I beg to differ.  Everything else uses your game logs which the game produces in excess.  How about just letting the user choose?  I presume directly logging into your user account gives the software access to more actual data, but the amount of data within the logs is monumental all the same.  So just let the user choose.  Login and get full data access, or no login and get more limited data access.  I love the idea of something nice and minimal rather than something extreme and over-the-top like EDDiscovery (which, btw, has gotten up to 7.40GiB on my system -- 4.33GiB with transparent filesystem compression enabled on its data folder) but it's just too dangerous that an account could be completely compromised.

Please at least consider it.
