### ISSUE TITLE
Installer for 3.35 broken

### ISSUE THREAD

**Issue by Fredyy90** [Marginal/EDMarketConnector#390]
Hey,

When i download the new version and try to install it, get this Windows Error. Seems to be a problem with some transformed paths and as far as I understand after a short googling its windows language related.
![image](https://user-images.githubusercontent.com/1572327/50957121-b7690b80-14bd-11e9-9554-97db9ce5ae8e.png)

Im on German Windows 10, with all Updates Installed, and EDMC 3.30 earlier EDMC Installer versions worked fine. The problem must have been introduced somewhere between 3.30 and 3.35

**Comment by magni1200s** [comment]
Seems that the installer causes an error if the system language is not set to English. The error message is "Error applying transforms. Verify that the specified transform paths are valid.".
![2019-01-10_00001](https://user-images.githubusercontent.com/7367597/50961394-fa050500-150a-11e9-8974-6f9c2198a5ed.png)

An workaround for this issue is to set the system language to English temporary. For Windows 10, 
1. Go to Start menu, then select "PC settings"
2. On Windows Settings, select "Time & Language", then select "Language"
3. Set "Windows display language"  to "English". If you cannot select English, you need to add an English language pack. 
4. Run the installer EDMarketConnector_win_335.msi
5. Restore "Windows display language"  to your language

**Comment by Marginal** [comment]
Installation on non-English systems should be fixed in [Release 3.36](https://github.com/Marginal/EDMarketConnector/releases/latest). Sorry about that.

**Comment by Fredyy90** [comment]
yes its fixed, just updated to 3.36 without a problem.

thank you for the fast response and fix
