### ISSUE TITLE
The special modules aren't displayed into the data sent to Eddn

### ISSUE THREAD

**Issue by koreldan** [Marginal/EDMarketConnector#40]
example: there's no prismatic shields into the data that arrive to eddn

**Comment by AnthorNet** [comment]
They should be, see here:
https://github.com/Marginal/EDMarketConnector/blob/master/outfitting.py#L211

**Comment by koreldan** [comment]
yep, i saw them... but in Eddn there are no "Prismatic Shield Generator" into data logs

**Comment by AnthorNet** [comment]
I don't have them in database, have you seen them in game?

**Comment by AnthorNet** [comment]
According to EDDB, lot of prismatic have been received.

**Comment by koreldan** [comment]
yep
At the "Jormor" system into "Cardano Port" i harvested the outfiting's datas by edce_client.py that gives me original datas from "companion app"

a prismatic shield is displayed like this:
      '128671323': {
        'id': 128671323,
        'cost': 132200,
        'category': 'powerplay',
        'name': 'Int_ShieldGenerator_Size1_Class5_Strong',
        'sku': 'ELITE_SPECIFIC_V_POWER_100000'
      },

this datas are correctly managed by EDMC as you showed me, but this data doesn't arrive at Eddn correctly or... Eddn changes its name... dunno.

**Comment by AnthorNet** [comment]
Well EDDN don't change anything on the received JSON.

But EDMC should send something like that:
```json
{
    "category": "internal",
    "rating": "A",
    "name": "Prismatic Shield Generator",
    "class": "2"
}
```

**Comment by Marginal** [comment]
PP-specific modules and other modules that depend on the commander's rank or affiliation are only visible in the data returned from the Companion API if you are eligible for the module.

This presents a problem for EDDN because it makes the data unstable - a Cmr will send a list of modules for a station and then a minute later another commander will send a different list. So the schema [says](https://github.com/jamesremuscat/EDDN/blob/master/schemas/outfitting-v1.0.json#L45) that such modules should be omitted - which is what EDMC [does](https://github.com/Marginal/EDMarketConnector/blob/master/outfitting.py#L241).

In practise, I believe that PP-specific modules are always available (to those who are eligible) when the "base" version of the module is available. I think that's the logic that EDDB is using.

**Comment by AnthorNet** [comment]
So my bad ;)
I should add them to my database :D

**Comment by koreldan** [comment]
looking into these logs : https://ross.eddb.io/eddn/log

there's no reference to any prismatic shield at any station :\

**Comment by koreldan** [comment]
i'm wondering if this kind of issue affects all "special" modules.

**Comment by koreldan** [comment]
at Cardano Port - Jormor there are:

specials shield:
size | class
1     |  5
2     |  5
3     |  5
4     |  5
5     |  5
6     |  5
7     |  5
8     |  5

normal shield:
from size  2 to size 6 and just size 2 and 3 have class 5.

In this case the normal modules availability doesn't reflect the availability of special modules.

**Comment by Marginal** [comment]
> In this case the normal modules availability doesn't reflect the availability of special modules.

I've also read on the forums that they're all available at stations that supply outfitting, which your findings seem to confirm. Can you try some other stations?

> They could be simply marked as "powerplay_modules" = 1

That doesn't help with the data instability issue. The outfitting message is supposed to indicate *all* modules that are currently available at a station (because modules can go out of stock). Under this idea, if a player's outfitting message doesn't include Prismatic Shields what does this indicate about whether the station sells them?

**Comment by Marginal** [comment]
FYI the [wiki](http://elite-dangerous.wikia.com/wiki/Prismatic_Shield_Generator#Acquisition) says "As soon as the player unlocks the Prismatic Shield Generator all large stations (even in hostile systems) will sell it for all module-classes from A1 - A8.[citation needed]".

**Comment by koreldan** [comment]
I meant simply that they could be managed as 4th batch of data ( like "commodities", "modules" or "ships" are ) if the player has the possibility to send those datas...

This shouldn't affect eddn stability but simply has to implement that 4th schema

**Comment by Marginal** [comment]
> I meant simply that they could be managed as 4th batch of data ( like "commodities", "modules" or "ships" are ) if the player has the possibility to send those datas...

If the wiki is correct then these messages would be redundant.

**Comment by koreldan** [comment]
yep, like the ships availability is, till new ships are implemented by Frontiers

**Comment by Marginal** [comment]
Looking at my logs from July it seems that my PP-specific weapon was available:
- in Systems not controlled or exploited by my Power
- at a least one station where the "base" module was not available

And I didn't find any stations that supplied outfitting but that _didn't_ stock my PP-specific weapon.

So it looks to me that PP-specific modules are available (to those who are eligible) at any station that supplies outfitting.

**Comment by AnthorNet** [comment]
In controlled or not controlled?

**Comment by koreldan** [comment]
At the moment:
- the larger update is about 8 modules for prismatic shields
- those data are available from "companion's api"
- Frontiers stated that they can change or add content live
- every tools add those powerplay modules supposing that the rule for prismatic shields still be valid for all power play modules, this hoping that rule still be valid since the date that info was inserted

**Comment by Marginal** [comment]
> In controlled or not controlled?

Both. I've edited that comment.

> those data are available from "companion's api"

Only to those players who are eligible for the module, which is a small percentage of the player base. So the data will be very incomplete.

If PP-specific modules become hard to find in the future then this might be worth contemplating, but right now it seems pointless to me.

**Comment by koreldan** [comment]
so be it, thank you for your patience on replying to me ;)
