### ISSUE TITLE
Always on Top doesn't change anything in Linux (i3)

### ISSUE THREAD

**Issue by lehthanis** [Marginal/EDMarketConnector#421]
I don't have the ability to modify the checkbox for Always on Top.  And it's always on top, no matter which workspace I'm in.

**Comment by lehthanis** [comment]
I'm using i3-gaps as my DE if that matters.

**Comment by Marginal** [comment]
Unfortunately most WMs force undecorated windows to be always on top, so this option is greyed out if you're using the dark theme since it doesn't do anything. I don't know of any way to force the WM to treat the window as a normal window, just without decoration.

Choose the default theme if you don't want it always on top.
