### ISSUE TITLE
EDMarketConnector reporting erroneously that I'm not docked at any station

### ISSUE THREAD

**Issue by nemesyssoft** [Marginal/EDMarketConnector#45]
Not sure what is happening all of a sudden. I'm playing the regular 1.4.01 version. I'm docked at Rogers Hub in HIP 105391 but after 3 times and being there for at least 5 minutes, EDMarketConnector still reports that I'm not docked at any station when I try updating. It gets the correct system but doesn't seem all of a sudden to see that I'm actually docked.

UPDATE: just as I finish writing this, I do another try and this time, it correctly reported that I'm docked at Rogers Hub. I will keep an eye on it. Maybe just a temporary glitch.

**Comment by Marginal** [comment]
I've seen this on occasion - the servers hosting the Companion API that this app uses sometimes lag the main game servers. 'Though personally I've only seen it lag a few seconds rather than 5 minutes.
I think that interacting with station services can sometimes force it to notice that you're docked. If it happens again try entering Outfitting.

Going to close this as there's nothing I can do about it.
