### ISSUE TITLE
"Agronomic Treatment" comodity

### ISSUE THREAD

**Issue by nepomuk16321** [Marginal/EDMarketConnector#481]
Hello everybody,
the market list that is transferred to Trade Dangerous has an error. 
The "Agronomic Treatment" comodity is being transmitted written together 
(in this incorrect spelling "AgronomicTreatment").

![image](https://user-images.githubusercontent.com/20616775/76162198-7a3cef80-613b-11ea-8beb-d78e70d870c5.png)

Thanks and greetings from nepomuk

**Comment by Doc1337** [comment]
Hi, thank you for reporting. I was able to reproduce this and found fix. The reason you are having this issue is because the latest compiled [release](https://github.com/Marginal/EDMarketConnector/releases/tag/rel-343) has outdated .csv file for commodities. Fortunately you can easily fix this by going to your installation folder (defaulty located at):
`C:\Program Files (x86)\EDMarketConnector`
and overwriting `commodity.csv` with this [file](https://raw.githubusercontent.com/Marginal/EDMarketConnector/master/commodity.csv).
(Right click and save the file to your PC).

If this fixed your issue please close it. If you need any more help, I would be happy to provide some.

Have a nice day.

**Comment by nepomuk16321** [comment]
Hello Doc,
thank you for the fast help !
I'll try it out tomorrow. Thanks a lot.
If everything works I'll close here.

Greetings nepomuk

**Comment by nepomuk16321** [comment]
Hi Doc,

it works perfect !  

Thank you very much !

I close the ticket.
