### ISSUE TITLE
Option to disable EDSM checks

### ISSUE THREAD

**Issue by nnemkin** [Marginal/EDMarketConnector#56]
I'd love to see an option to completely disable all EDSM queries.

It's just leaking my exploration log without adding any value (Clicking on a system name link leads to login page).

**Comment by AnthorNet** [comment]
Hi.
EDSM is not registering your flight log if you do not provide your API with us.

If you go to a log in page when clicking I will have to check cause it should not be the case.

**Comment by Marginal** [comment]
EDMC looks up unpopulated systems in order to display whether they have known positions or are brand new. So it does effectively "leak" your exploration log ('though the data is not associated with you unless you have entered your details and have selected the option to send your flight log to EDSM).

This will be fixed in the next version - the system's status will only be looked up and displayed if you have selected the option to send your flight log to EDSM.

If you click on the "System" link in EDMC's window it will still send you to EDSM (and so "leak" your location) in either case.

**Comment by Marginal** [comment]
> If you go to a log in page when clicking I will have to check cause it should not be the case.

It is currently the case that you do need to be logged in to go to a system by name. e.g. http://www.edsm.net/needed-distances?systemName=Shinrarta%20Dezhra

**Comment by AnthorNet** [comment]
Yes please, I changed it some time ago. And there is also he urls  with ids.

**Comment by AnthorNet** [comment]
I am still wondering how it can leak anything ^^

**Comment by Marginal** [comment]
> And there is also he urls with ids

Yeah. But I don't know the ids without looking them up!

**Comment by AnthorNet** [comment]
I will look at the code today.
The url API have the good one with the id

**Comment by Marginal** [comment]
Fixed in 75cf0d6 and f239aec.

**Comment by nnemkin** [comment]
Great work :thumbsup:

**Comment by Marginal** [comment]
Fixed in Release 2.01
