### ISSUE TITLE
Status window doesn't scroll

### ISSUE THREAD

**Issue by DaveTheDrummer** [Marginal/EDMarketConnector#78]
Just started using this and it's massively impressive. Saved me a great deal of time already. Point I'm noting is that when I click Status the window opens no problem and the data is there no problem. But as I have ships in over 170 locations (no idea how many actual ships) the window is incredibly long and extends off the bottom of the screen for some distance so I can't get to it. Scroll bars would be handy.
![edmc_statusissue](https://cloud.githubusercontent.com/assets/16572155/12224424/f6f351e2-b7e7-11e5-8a8a-3f70fd999f38.jpg)
Related issue: How do I get the data out of the Status window? I'd like to be able to process it.
Thanks for a service that's saving me and many others plenty of time and is making a significant contribution to the game experience.

**Comment by Marginal** [comment]
Wow, your Galaxy Map must be littered with ship symbols. You can't scroll the window because I didn't consider the case where someone would have so many ships.

You can get access to the data behind the status window in one of two ways:
- If you [run from source](https://github.com/Marginal/EDMarketConnector/wiki/Running-from-source) the program dumps the raw data in a [JSON](http://www.json.org/) formatted file.
- If you have a basic familiarity with Python programming you can write a [plugin](https://github.com/Marginal/EDMarketConnector/blob/master/PLUGINS.md) to process the data.

**Comment by DaveTheDrummer** [comment]
Hehehe. There are quite a few yes.
![screenshot_0148a](https://cloud.githubusercontent.com/assets/16572155/12228336/b7769854-b831-11e5-8b49-2fbe6f4e718c.jpg)
I'll have a go at getting at it but I have no idea what most of that means. My programming days went out the window when people stopped needing machine code for 6502A 8 bit processors.
People who code these days are like wizards to me. I have almost zero idea how they do what they do, mainly I think because I don't understand high level languages.
Thanks again :-)
