### ISSUE TITLE
Not reporting planet approach suite

### ISSUE THREAD

**Issue by cmdrmcdonald** [Marginal/EDMarketConnector#91]
I note that in https://github.com/Marginal/EDMarketConnector/blob/ce81aa2e552607361aa31cbff0149ed742341e6d/outfitting.py#L202 you are stating "don't report" for the planet approach suite.  As this is a real module it would be useful if this was reported and showed up along with the rest of the modules, for some downstream systems at least.

**Comment by Marginal** [comment]
Neither of the output formats that EDMC supports include the Planetary Approach Suite. (Presumably because the Planetary Approach Suite has no mass and takes no space and is therefore effectively the same as a decal, paintjob or bobblehead).

So you will need to take this up with E:D Shipyard and/or [Coriolis](https://github.com/cmmcleod/coriolis).

**Comment by Marginal** [comment]
This is fixed in release 2.23 for E:D Shipyard and 2.24 for Coriolis.
